# Generated by Django 3.2.2 on 2022-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Complaint',
            name='Type_of_Print',
            field=models.CharField(choices=[('Colour-A4', 'Colour-A4'), ('Colour-A3', 'Colour-A3'), ('Black and White-A4', 'Black and White-A4'), ('Black and White-A3', 'Black and White-A3'), ('Other-Please mention in the Address box', 'Other-Please mention in the Address box')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('Cloud Computing', 'Cloud Computing'), ('Cyber Security', 'Cyber Security'), ('DA Group A', 'DA Group A'), ('DA Group B', 'DA Group B')], default='Technical', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Business', 'Business')], max_length=29),
        ),
    ]
